// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWyvA-DuyTf1nDC1Sc87zITK6P8_rbnpc',
    appId: '1:1055263672671:web:6cf38a989faa4b72488eea',
    messagingSenderId: '1055263672671',
    projectId: 'labs-mis',
    authDomain: 'labs-mis.firebaseapp.com',
    storageBucket: 'labs-mis.appspot.com',
    measurementId: 'G-TE1V5KJ17R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqK_HZV1IfnoPY2n2UiLDqktDX2qn6ILY',
    appId: '1:1055263672671:android:2eedc36939269c0e488eea',
    messagingSenderId: '1055263672671',
    projectId: 'labs-mis',
    storageBucket: 'labs-mis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEZbdyVeQUNDJha9acG25FVpAI4MYpMkg',
    appId: '1:1055263672671:ios:8f3c808902f3f676488eea',
    messagingSenderId: '1055263672671',
    projectId: 'labs-mis',
    storageBucket: 'labs-mis.appspot.com',
    iosBundleId: 'com.example.lab3Main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEZbdyVeQUNDJha9acG25FVpAI4MYpMkg',
    appId: '1:1055263672671:ios:5196ae20fe9e43f6488eea',
    messagingSenderId: '1055263672671',
    projectId: 'labs-mis',
    storageBucket: 'labs-mis.appspot.com',
    iosBundleId: 'com.example.lab3Main.RunnerTests',
  );
}
